/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseSmartMeterEchonetlitePropertiesInner {
    #[serde(rename = "epc", skip_serializing_if = "Option::is_none")]
    pub epc: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "val", skip_serializing_if = "Option::is_none")]
    pub val: Option<String>,
}

impl ApplianceResponseSmartMeterEchonetlitePropertiesInner {
    pub fn new() -> ApplianceResponseSmartMeterEchonetlitePropertiesInner {
        ApplianceResponseSmartMeterEchonetlitePropertiesInner {
            epc: None,
            name: None,
            updated_at: None,
            val: None,
        }
    }
}

