/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseAircon {
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<Box<models::ApplianceResponseAirconRange>>,
    #[serde(rename = "tempUnit", skip_serializing_if = "Option::is_none")]
    pub temp_unit: Option<String>,
}

impl ApplianceResponseAircon {
    pub fn new() -> ApplianceResponseAircon {
        ApplianceResponseAircon {
            range: None,
            temp_unit: None,
        }
    }
}

