/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseTv {
    #[serde(rename = "buttons", skip_serializing_if = "Option::is_none")]
    pub buttons: Option<Vec<models::ApplianceResponseLightButtonsInner>>,
    #[serde(rename = "layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<Vec<models::ApplianceResponseTvLayoutInner>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::ApplianceResponseTvState>>,
}

impl ApplianceResponseTv {
    pub fn new() -> ApplianceResponseTv {
        ApplianceResponseTv {
            buttons: None,
            layout: None,
            state: None,
        }
    }
}

