/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseEchonetliteLocalize {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, models::ApplianceResponseEchonetliteLocalizePropertiesValue>>,
}

impl ApplianceResponseEchonetliteLocalize {
    pub fn new() -> ApplianceResponseEchonetliteLocalize {
        ApplianceResponseEchonetliteLocalize {
            properties: None,
        }
    }
}

