/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseAirconRangeModesValue {
    #[serde(rename = "dir", skip_serializing_if = "Option::is_none")]
    pub dir: Option<Vec<String>>,
    #[serde(rename = "dirh", skip_serializing_if = "Option::is_none")]
    pub dirh: Option<Vec<String>>,
    #[serde(rename = "temp", skip_serializing_if = "Option::is_none")]
    pub temp: Option<Vec<String>>,
    #[serde(rename = "vol", skip_serializing_if = "Option::is_none")]
    pub vol: Option<Vec<String>>,
}

impl ApplianceResponseAirconRangeModesValue {
    pub fn new() -> ApplianceResponseAirconRangeModesValue {
        ApplianceResponseAirconRangeModesValue {
            dir: None,
            dirh: None,
            temp: None,
            vol: None,
        }
    }
}

