/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseEchonetliteLocalizePropertiesValue {
    #[serde(rename = "enum", skip_serializing_if = "Option::is_none")]
    pub r#enum: Option<std::collections::HashMap<String, models::ApplianceResponseEchonetliteLocalizePropertiesValueEnumValue>>,
}

impl ApplianceResponseEchonetliteLocalizePropertiesValue {
    pub fn new() -> ApplianceResponseEchonetliteLocalizePropertiesValue {
        ApplianceResponseEchonetliteLocalizePropertiesValue {
            r#enum: None,
        }
    }
}

