/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseAirconSmartEcoMode {
    #[serde(rename = "adjusting", skip_serializing_if = "Option::is_none")]
    pub adjusting: Option<bool>,
    #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
    pub area: Option<i32>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl ApplianceResponseAirconSmartEcoMode {
    pub fn new() -> ApplianceResponseAirconSmartEcoMode {
        ApplianceResponseAirconSmartEcoMode {
            adjusting: None,
            area: None,
            enabled: None,
        }
    }
}

