/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseEchonetliteGetPropertiesValue {
    #[serde(rename = "enum", skip_serializing_if = "Option::is_none")]
    pub r#enum: Option<Vec<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl ApplianceResponseEchonetliteGetPropertiesValue {
    pub fn new() -> ApplianceResponseEchonetliteGetPropertiesValue {
        ApplianceResponseEchonetliteGetPropertiesValue {
            r#enum: None,
            r#type: None,
        }
    }
}

