/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceModelAndParam {
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::ApplianceModelAndParamModel>>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<models::ApplianceModelAndParamParams>>,
}

impl ApplianceModelAndParam {
    pub fn new() -> ApplianceModelAndParam {
        ApplianceModelAndParam {
            model: None,
            params: None,
        }
    }
}

