/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseEchonetliteLocalizePropertiesValueEnumValue {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl ApplianceResponseEchonetliteLocalizePropertiesValueEnumValue {
    pub fn new() -> ApplianceResponseEchonetliteLocalizePropertiesValueEnumValue {
        ApplianceResponseEchonetliteLocalizePropertiesValueEnumValue {
            label: None,
        }
    }
}

