/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApplianceResponseEchonetlite : The ECHONET lite properties fetched from the appliance. See 'Detailed Requirements for ECHONET Device Objects' for more details. ref. https://echonet.jp/spec_object_rl_en/
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseEchonetlite {
    #[serde(rename = "get_properties", skip_serializing_if = "Option::is_none")]
    pub get_properties: Option<std::collections::HashMap<String, models::ApplianceResponseEchonetliteGetPropertiesValue>>,
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(rename = "localize", skip_serializing_if = "Option::is_none")]
    pub localize: Option<Box<models::ApplianceResponseEchonetliteLocalize>>,
    #[serde(rename = "route_type", skip_serializing_if = "Option::is_none")]
    pub route_type: Option<String>,
    #[serde(rename = "set_properties", skip_serializing_if = "Option::is_none")]
    pub set_properties: Option<std::collections::HashMap<String, models::ApplianceResponseEchonetliteGetPropertiesValue>>,
    #[serde(rename = "state", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state: Option<Option<serde_json::Value>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ApplianceResponseEchonetlite {
    /// The ECHONET lite properties fetched from the appliance. See 'Detailed Requirements for ECHONET Device Objects' for more details. ref. https://echonet.jp/spec_object_rl_en/
    pub fn new() -> ApplianceResponseEchonetlite {
        ApplianceResponseEchonetlite {
            get_properties: None,
            identifier: None,
            instance: None,
            ip: None,
            localize: None,
            route_type: None,
            set_properties: None,
            state: None,
            version: None,
        }
    }
}

