/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseMorninPlus {
    #[serde(rename = "devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<Vec<models::ApplianceResponseMorninPlusDevicesInner>>,
    #[serde(rename = "hi_speed_mode", skip_serializing_if = "Option::is_none")]
    pub hi_speed_mode: Option<bool>,
}

impl ApplianceResponseMorninPlus {
    pub fn new() -> ApplianceResponseMorninPlus {
        ApplianceResponseMorninPlus {
            devices: None,
            hi_speed_mode: None,
        }
    }
}

