/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplianceResponseAirconRange {
    #[serde(rename = "fixedButtons", skip_serializing_if = "Option::is_none")]
    pub fixed_buttons: Option<Vec<String>>,
    #[serde(rename = "modes", skip_serializing_if = "Option::is_none")]
    pub modes: Option<std::collections::HashMap<String, models::ApplianceResponseAirconRangeModesValue>>,
}

impl ApplianceResponseAirconRange {
    pub fn new() -> ApplianceResponseAirconRange {
        ApplianceResponseAirconRange {
            fixed_buttons: None,
            modes: None,
        }
    }
}

