/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EchonetLiteApplianceResponseAppliancesInner {
    #[serde(rename = "Device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<models::ApplianceResponseDevice>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<models::EchonetLiteApplianceResponseAppliancesInnerPropertiesInner>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl EchonetLiteApplianceResponseAppliancesInner {
    pub fn new() -> EchonetLiteApplianceResponseAppliancesInner {
        EchonetLiteApplianceResponseAppliancesInner {
            device: None,
            id: None,
            nickname: None,
            properties: None,
            r#type: None,
        }
    }
}

