/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EchonetLiteApplianceResponse {
    #[serde(rename = "appliances", skip_serializing_if = "Option::is_none")]
    pub appliances: Option<Vec<models::EchonetLiteApplianceResponseAppliancesInner>>,
}

impl EchonetLiteApplianceResponse {
    pub fn new() -> EchonetLiteApplianceResponse {
        EchonetLiteApplianceResponse {
            appliances: None,
        }
    }
}

