/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HomeInvite {
    #[serde(rename = "home", skip_serializing_if = "Option::is_none")]
    pub home: Option<Box<models::HomeInviteHome>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::HomeInviteUser>>,
}

impl HomeInvite {
    pub fn new() -> HomeInvite {
        HomeInvite {
            home: None,
            url: None,
            user: None,
        }
    }
}

