/*
 * Nature API
 *
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponseUpdatedPrivacyPolicy {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<std::collections::HashMap<String, models::UserResponseUpdatedPrivacyPolicyLinksValue>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl UserResponseUpdatedPrivacyPolicy {
    pub fn new() -> UserResponseUpdatedPrivacyPolicy {
        UserResponseUpdatedPrivacyPolicy {
            body: None,
            links: None,
            title: None,
        }
    }
}

