[package]
name = "remo-home"
edition = "2021"
authors.workspace = true
version.workspace = true

[dependencies]
remo-sdk = { path = "../remo-sdk" }
dotenvy = "0.15.7"
eyre = "0.6.12"
tokio = { version = "1.43.0", features = ["full"] }
clap = { version = "4.5.26", features = ["derive"] }
